version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3001/api
    depends_on:
      - backend
    networks:
      - permata-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/database.sqlite:/app/database.sqlite
      - ./backend/uploads:/app/uploads
    environment:
      - NODE_ENV=development
      - PORT=3001
      - JWT_SECRET=your-super-secret-jwt-key-here
      - CORS_ORIGIN=http://localhost:5173
    networks:
      - permata-network

networks:
  permata-network:
    driver: bridge
